import React from 'react';
import { createElement as h } from 'react';
import { useScope, useWorkspaceSnapshot, configOf, workspaceId, workspaceLabel } from '../utils.js';
import { Dialog, CategoryForm, Confirm } from './dialogs.jsx';
function CategorySection({ api, t }) {
      const scope = api.settingsScope; const settings = useScope(scope); const list = useWorkspaceSnapshot(api.workspacesList).items ?? []; const config = configOf(scope); const [dialog, setDialog] = React.useState(null); const [failure, setFailure] = React.useState('');
      const write = async (patch) => { try { setFailure(''); for (const [key, value] of Object.entries(patch)) await scope.set(key, value); } catch (error) { setFailure(errText(error)); } };
      const saveCategory = (category) => { const originalId = dialog?.kind === 'edit' ? dialog.category.id : undefined; if (originalId !== undefined && originalId !== category.id) return setFailure('分类标识符创建后不可修改。'); if (originalId === undefined && config.categories.some((item) => item.id === category.id)) return setFailure('分类标识符已存在。'); write({ categories: originalId === undefined ? [...config.categories, category] : config.categories.map((item) => item.id === category.id ? category : item) }); setDialog(null); };
      const removeCategory = (category) => { const assignments = Object.fromEntries(Object.entries(config.assignments).filter(([, categoryId]) => categoryId !== category.id)); write({ categories: config.categories.filter((item) => item.id !== category.id), assignments }); setDialog(null); };
      const assign = (id, categoryId) => { const assignments = { ...config.assignments }; if (categoryId === '') delete assignments[id]; else assignments[id] = categoryId; write({ assignments }); };
      if (settings.status === 'loading') return h('p', { className: 'wcm-muted' }, t('loading')); if (settings.status !== 'ready') return h('p', { className: 'wcm-error' }, t('unavailable'));
      return h('div', { className: 'wcm' }, h('h2', null, t('title')), h('p', { className: 'wcm-intro' }, t('intro')), h('p', { className: 'wcm-muted' }, t('nonDestructive')), failure ? h('p', { className: 'wcm-error' }, failure) : null, h('div', { className: 'wcm-head' }, h('h3', null, t('categoryTitle')), h('button', { className: 'wcm-primary', disabled: !settings.writable, onClick: () => setDialog({ kind: 'add' }) }, t('addCategory'))), h('div', { className: 'wcm-list' }, config.categories.length === 0 ? h('p', { className: 'wcm-muted' }, t('emptyCategories')) : config.categories.map((category) => { const total = Object.values(config.assignments).filter((id) => id === category.id).length; return h('article', { className: 'wcm-card', key: category.id }, h('div', { className: 'wcm-row' }, h('div', null, h('div', { className: 'wcm-title' }, h('span', { className: 'wcm-dot', style: { background: category.color } }), category.name), h('div', { className: 'wcm-meta' }, `${category.id} · ${t('assignedCount', { count: total })}`)), h('div', { className: 'wcm-actions', style: { marginTop: 0 } }, h('button', { onClick: () => setDialog({ kind: 'edit', category }) }, t('edit')), h('button', { className: 'wcm-danger', onClick: () => setDialog({ kind: 'remove', category }) }, t('remove'))))); })), h('h3', null, t('workspaceTitle')), h('div', { className: 'wcm-list' }, list.length === 0 ? h('p', { className: 'wcm-muted' }, t('emptyWorkspaces')) : list.map((workspace) => { const id = workspaceId(workspace); return h('article', { className: 'wcm-card', key: id }, h('div', { className: 'wcm-row' }, h('div', null, h('div', { className: 'wcm-title' }, workspaceLabel(workspace)), h('div', { className: 'wcm-meta' }, workspace.path)), h('select', { className: 'wcm-select', value: config.assignments[id] ?? '', disabled: !settings.writable, onChange: (event) => assign(id, event.target.value) }, h('option', { value: '' }, t('uncategorized')), config.categories.map((category) => h('option', { key: category.id, value: category.id }, category.name))))); })), dialog?.kind === 'add' ? h(Dialog, { title: t('addCategory'), close: () => setDialog(null) }, h(CategoryForm, { initial: { id: '', name: '', color: colors[config.categories.length % colors.length] }, save: saveCategory, cancel: () => setDialog(null) })) : null, dialog?.kind === 'edit' ? h(Dialog, { title: t('editCategory'), close: () => setDialog(null) }, h(CategoryForm, { initial: dialog.category, lockedId: true, save: saveCategory, cancel: () => setDialog(null) })) : null, dialog?.kind === 'remove' ? h(Confirm, { title: t('removeCategory'), text: t('removeConfirm', { name: dialog.category.name }), close: () => setDialog(null), confirm: () => removeCategory(dialog.category) }) : null);
    }
export { CategorySection };
