import React from 'react';
import { createElement as h } from 'react';
import cssText from './styles.css';
import { NS, SETTINGS_NAMESPACE } from './constants.js';
import { createDshApi } from './api.js';
import { CategorySection } from './components/CategorySection.jsx';
import { CategorySidebar } from './components/CategorySidebar.jsx';

if (typeof document !== 'undefined') { const tagId = 'dsh-workspace-category-manager/styles.css'; if (document.querySelector(`style[data-plugin-css="${tagId}"]`) === null) { const tag = document.createElement('style'); tag.dataset.plugin = 'dsh-workspace-category-manager'; tag.dataset.pluginCss = tagId; tag.textContent = cssText; document.head.appendChild(tag); } }

const zh = { title: '工作区分类', intro: '创建分类并把左侧工作区中的项目归入分类。分类会立即显示在工作区列表中。', nonDestructive: '分类只保存“工作区 ID → 分类”关系：不会移动、重命名或删除磁盘上的项目目录。', categoryTitle: '分类目录', workspaceTitle: '工作区', addWorkspace: '添加工作区', chooseGroup: '选择分组', chooseDirectory: '项目目录', directoryPlaceholder: '点击“浏览”选择目录', browse: '浏览', noCategoriesHint: '还没有分类，可直接以“未分类”创建，稍后在设置中归组。', addCategory: '新增分类', editCategory: '编辑分类', removeCategory: '删除分类', emptyCategories: '尚未创建分类。未分类项目会直接显示在侧栏中。', emptyWorkspaces: '没有已注册的工作区。请从左侧工作区区域添加项目。', uncategorized: '未分类', all: '全部', newSession: '新会话', emptyFiltered: '该分类下暂无项目。', viewOptions: '视图选项', orderByLabel: '排序方式', orderManual: '手动排序', orderUpdated: '最近更新', close: '关闭', retry: '重试', addWorkspaceError: '添加工作区失败', rename: '重命名', renameWorkspaceTitle: '重命名工作区', renameSessionTitle: '重命名会话', fork: '分叉会话', archive: '归档会话', deleteWorkspace: '删除工作区', deleteWorkspaceText: '将把“{name}”从工作区列表中移除。文件夹与会话记录会保留，其会话将显示在“未分类”下。', workspaceMenu: '工作区操作', sessionMenu: '会话操作', dissolveCategory: '解散分类', dissolveCategoryText: '确定解散分类“{name}”吗？该分类下的所有项目将进入未分类。', categoryIdExists: '分类标识符已存在。', cancel: '取消', save: '保存', confirm: '确认', edit: '编辑', remove: '删除', loading: '正在读取设置…', unavailable: '当前部署未提供可编辑的分类设置。', assignedCount: '{count} 个项目', removeConfirm: '确定删除“{name}”吗？该分类下的项目将恢复为未分类。' };
    const en = { title: 'Workspace categories', intro: 'Create categories and assign the projects in the left workspace list. Categories are reflected in the sidebar immediately.', nonDestructive: 'Categories store only a workspace-ID-to-category mapping. Project directories are never moved, renamed, or deleted.', categoryTitle: 'Categories', workspaceTitle: 'Workspaces', addWorkspace: 'Add workspace', chooseGroup: 'Choose a category', chooseDirectory: 'Project directory', directoryPlaceholder: 'Click “Browse” to choose a directory', browse: 'Browse', noCategoriesHint: 'No categories yet — create it as Uncategorized and organize it later in Settings.', addCategory: 'Add category', editCategory: 'Edit category', removeCategory: 'Remove category', emptyCategories: 'No categories yet. Uncategorized projects appear directly in the sidebar.', emptyWorkspaces: 'No registered workspaces. Add a project from the left workspace area.', uncategorized: 'Uncategorized', all: 'All', newSession: 'New Session', emptyFiltered: 'No projects in this category.', viewOptions: 'View options', orderByLabel: 'Sort by', orderManual: 'Manual', orderUpdated: 'Recently updated', close: 'Close', retry: 'Retry', addWorkspaceError: 'Failed to add workspace', rename: 'Rename', renameWorkspaceTitle: 'Rename workspace', renameSessionTitle: 'Rename session', fork: 'Fork session', archive: 'Archive session', deleteWorkspace: 'Delete workspace', deleteWorkspaceText: 'This removes “{name}” from the workspace list. The folder and session logs will be kept. Its sessions will appear under Uncategorized.', workspaceMenu: 'Workspace actions', sessionMenu: 'Session actions', dissolveCategory: 'Dissolve category', dissolveCategoryText: 'Dissolve category “{name}”? All its projects will move to Uncategorized.', categoryIdExists: 'Category id already exists.', cancel: 'Cancel', save: 'Save', confirm: 'Confirm', edit: 'Edit', remove: 'Remove', loading: 'Loading settings…', unavailable: 'This deployment does not expose editable category settings.', assignedCount: '{count} project(s)', removeConfirm: 'Remove “{name}”? Its projects will become uncategorized.' };
    const inject = ['slots', 'locale', 'settingsScope', 'workspaces', 'sessions'];
    function apply(ctx) { ctx.effect(() => ctx.locale.register(NS, { zh, en }), 'workspace-category-manager: dictionaries'); const t = ctx.locale.bind(NS); const api = createDshApi(ctx); ctx.slots.inject('settings.section', () => ctx.slots.register({ name: 'settings.section', id: 'workspace-categories', order: 16, label: () => t('title'), locale: NS, inject: () => ({ api, t }) }, CategorySection)); ctx.slots.inject('sidebar.workspaces', () => ctx.slots.register({ name: 'sidebar.workspaces', priority: -1, locale: NS, inject: () => ({ api, t }) }, CategorySidebar)); }
    export { apply, inject };

